version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3010:3005"
    command: bun run start
    restart: always
